---
title: "analise_rais_real"
description: |
  A short description of the post.
author:
  - name: Andres David Pinto Hurtado
    url: https://example.com/norajones
date: 2021-12-08
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Neste relatório estamos interessados em responder a pergunta:

"Quanto ganha um cientista de dados?"

Para isso vamos utilizar a base da RAIS anonimizada

# Acessando os dados da RAIS

Vamos utilizar [o datalake da iniciativa base dos dados ](https://basedosdados.org/dataset/br-me-rais).

```{r message=FALSE, warning=FALSE}

library(bigrquery)
library(dplyr)

```

Abaixo esta o código que carrega as primeiras 5 linhas da tabela microdados

```{r}
# Como eu faria se fosse ler um arquivo

# tabela_normal <- read.csv("https://raw.githubusercontent.com/curso-r/main-r4ds-1/master/dados/imdb.csv")
#
# head(tabela_normal, 5)

# Como eu faco se uso um SGBD (Sistema de gerenciamento de bases de dados)

conexao <- dbConnect(
  bigquery(),
  project = "basedosdados",
  dataset = "br_me_rais",
  billing = "semana-dsp-334503"
)

primeiras_cinco_linhas <- collect(head(select(tbl(conexao, "microdados_vinculos"), everything()), 5))

primeiras_cinco_linhas

```



